server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /data/promtail/positions.yml

clients:
  - url: http://dualla:3100/loki/api/v1/push
    external_labels:
      promtail: 'stubborn'

scrape_configs:
- job_name: stubborn-to
  static_configs:
  - targets:
      - localhost
    labels:
      job: to
      __path__: /var/stubborn/to.json
  pipeline_stages:
    - json:
        expressions:
          NOW: NOW 
    - timestamp:
        source: NOW
        format: Unix
    - labels:
        ERR:
    - metrics:
        uptime: 
          type: Gauge
          source: UP
          config:
            action: set
        loop:
          type: Histogram
          source: LOOP
          config:
            action: add

- job_name: journald
  journal:
    json: true
    path: /var/log/journal
    labels:
      job: journald
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: containers
  entry_parser: raw

  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
