#!/bin/bash

# XXX: ran clean to fix a bug, but maybe this is always necessary.
if ! arduino-cli compile -b arduino:avr:uno --libraries ../libraries -u -p /dev/tty.usbmodem14101 ground.ino; then
  echo >&2 "Upload failure"
  exit 1
fi

echo "done"